### ISSUE TITLE
Flow is aborted due to ['image_encoder', 'audio_encoder'] can not be started

### ISSUE THREAD

**Issue by sephib** [jina-ai/example-video-search#4]
Hi,
I'm running on a macOS 12.0.1
While trying to run the example (AS-IS)  I'm getting the following errors:

> image_encoder@90235[E]:Exception('the container fails to start, check the arguments or entrypoint') during <class 'jina.peapods.runtimes.container.ContainerRuntime'> initialization
...
> audio_encoder@90246[E]:Exception('the container fails to start, check the arguments or entrypoint') during <class 'jina.peapods.runtimes.container.ContainerRuntime'> initialization

Any assistance would be appreciated 

<details><summary>Here is the full trace</summary>
<p>

```bash
(base) ➜  example-video-search git:(main) ✗ python app.py

UserWarning: It looks like you are trying to import multiple python modules using `py_modules`. When using multiple python files to define an executor, the recommended practice is to structure the files in a python package, and only import the `__init__.py` file of that package. For more details, please check out the cookbook: https://docs.jina.ai/fundamentals/executor/repository-structure/ (raised from /Users/sephi/git_forked/example-video-search/.direnv/python-3.9.5/lib/python3.9/site-packages/jina/jaml/helper.py:242)
UserWarning: 
            executor shadows one of built-in Python module name.
            It is imported as `user_module.executor`

            Affects:
            - Either, change your code from using `from executor import ...`
              to `from user_module.executor import ...`
            - Or, rename executor to another name
             (raised from /Users/sephi/git_forked/example-video-search/.direnv/python-3.9.5/lib/python3.9/site-packages/jina/importer.py:111)
UserWarning: It looks like you are trying to import multiple python modules using `py_modules`. When using multiple python files to define an executor, the recommended practice is to structure the files in a python package, and only import the `__init__.py` file of that package. For more details, please check out the cookbook: https://docs.jina.ai/fundamentals/executor/repository-structure/ (raised from /Users/sephi/git_forked/example-video-search/.direnv/python-3.9.5/lib/python3.9/site-packages/jina/jaml/helper.py:242)
UserWarning: 
            executor shadows one of built-in Python module name.
            It is imported as `user_module.executor`

            Affects:
            - Either, change your code from using `from executor import ...`
              to `from user_module.executor import ...`
            - Or, rename executor to another name
             (raised from /Users/sephi/git_forked/example-video-search/.direnv/python-3.9.5/lib/python3.9/site-packages/jina/importer.py:111)
⠙ 8/10 waiting image_encoder audio_encoder to be ready...  image_encoder@64132[I]:                  
  image_encoder@64132[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  image_encoder@64132[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  image_encoder@64132[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  image_encoder@64132[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  image_encoder@64132[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  image_encoder@64132[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  image_encoder@64132[I]:MMMMMMMMMMMMWxxxxxxxxxOMMMMMNxxxxxxxxx0MMMMMKddddddxkKWMMMMMMMMMMMMXOxdddxONMMMM
  image_encoder@64132[I]:MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOllllllllllo0MMMMMMMM0olllllllllo0MM
  image_encoder@64132[I]:MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOlllllllllllloWMMMMMdllllllllllllldM
  image_encoder@64132[I]:MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOllllllllllllloMMMM0lllllllllllllllK
  image_encoder@64132[I]:MMMMMMMMMMMMKllllllllldMMMMM0lllllllllxMMMMMOllllllllllllllKMMM0lllllllllllllllO
  image_encoder@64132[I]:MMMMMMMMMMMMKllllllllldMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMollllllllllllllO
  image_encoder@64132[I]:MWOkkkkk0MMMKlllllllllkMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMMxlllllllllllllO
  image_encoder@64132[I]:NkkkkkkkkkMMKlllllllloMMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMMMWOdolllllllllO
  image_encoder@64132[I]:KkkkkkkkkkNMKllllllldMMMMMMMMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  image_encoder@64132[I]:MOkkkkkkk0MMKllllldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  image_encoder@64132[I]:MMWX00KXMMMMXxk0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  image_encoder@64132[I]:
  image_encoder@64132[I]:▶️  /usr/local/bin/jina executor --uses config.yml --name image_encoder --workspace /Users/sephi/git_forked/example-video-search --identity 5627a0e8-a635-4863-bcab-ab4e5608715f --workspace-id ceb0455c-0b52-447b-8b00-77dd84264f03 --zmq-identity 1332449d-1aac-4038-bd33-22dd03f1d681 --port-ctrl 52448 --uses-with {"traversal_paths": ["c"]} --port-in 52449 --port-out 52450 --hosts-in-connect --socket-in ROUTER_BIND --socket-out ROUTER_BIND --native --num-part 1 --dynamic-routing-out --dynamic-routing-in --runs-in-docker --upload-files --noblock-on-start
  image_encoder@64132[I]:🔧️                            cli = executor                      
  image_encoder@64132[I]:ctrl-with-ipc = False
  image_encoder@64132[I]:daemon = False
  image_encoder@64132[I]:disable-remote = False
  image_encoder@64132[I]:docker-kwargs = None
  image_encoder@64132[I]:dump-path =
  image_encoder@64132[I]:🔧️             dynamic-routing-in = True                          
  image_encoder@64132[I]:🔧️            dynamic-routing-out = True                          
  image_encoder@64132[I]:entrypoint = None
  image_encoder@64132[I]:env = None
  image_encoder@64132[I]:expose-public = False
  image_encoder@64132[I]:force = False
  image_encoder@64132[I]:gpus = None
  image_encoder@64132[I]:grpc-data-requests = False
  image_encoder@64132[I]:host = 0.0.0.0
  image_encoder@64132[I]:host-in = 0.0.0.0
  image_encoder@64132[I]:host-out = 0.0.0.0
  image_encoder@64132[I]:🔧️               hosts-in-connect = []                            
  image_encoder@64132[I]:🔧️                       identity = 5627a0e8-a635-4863-bcab-ab4e56
  image_encoder@64132[I]:install-requirements = False
  image_encoder@64132[I]:k8s-connection-pool = True
  image_encoder@64132[I]:k8s-namespace = None
  image_encoder@64132[I]:log-config = /usr/local/lib/python3.7/site-
  image_encoder@64132[I]:memory-hwm = -1
  image_encoder@64132[I]:🔧️                           name = image_encoder                 
  image_encoder@64132[I]:🔧️                         native = True                          
  image_encoder@64132[I]:🔧️               noblock-on-start = True                          
  image_encoder@64132[I]:🔧️                       num-part = 1                             
  image_encoder@64132[I]:on-error-strategy = IGNORE
  image_encoder@64132[I]:pea-id = 0
  image_encoder@64132[I]:pea-role = SINGLETON
  image_encoder@64132[I]:🔧️                      port-ctrl = 52448                         
  image_encoder@64132[I]:🔧️                        port-in = 52449                         
  image_encoder@64132[I]:port-jinad = 8000
  image_encoder@64132[I]:🔧️                       port-out = 52450                         
  image_encoder@64132[I]:pull-latest = False
  image_encoder@64132[I]:py-modules = None
  image_encoder@64132[I]:quiet = False
  image_encoder@64132[I]:quiet-error = False
  image_encoder@64132[I]:quiet-remote-logs = False
  image_encoder@64132[I]:routing-table = None
  image_encoder@64132[I]:🔧️                 runs-in-docker = True                          
  image_encoder@64132[I]:runtime-backend = PROCESS
  image_encoder@64132[I]:runtime-cls = ZEDRuntime
  image_encoder@64132[I]:🔧️                      socket-in = ROUTER_BIND                   
  image_encoder@64132[I]:🔧️                     socket-out = ROUTER_BIND                   
  image_encoder@64132[I]:ssh-keyfile = None
  image_encoder@64132[I]:ssh-password = None
  image_encoder@64132[I]:ssh-server = None
  image_encoder@64132[I]:static-routing-table = False
  image_encoder@64132[I]:timeout-ctrl = 5000
  image_encoder@64132[I]:timeout-ready = 600000
  image_encoder@64132[I]:🔧️                   upload-files = []                            
  image_encoder@64132[I]:🔧️                           uses = config.yml                    
  image_encoder@64132[I]:uses-metas = None
  image_encoder@64132[I]:uses-requests = None
  image_encoder@64132[I]:🔧️                      uses-with = {'traversal_paths': ['c']}    
  image_encoder@64132[I]:volumes = None
  image_encoder@64132[I]:🔧️                      workspace = /Users/sephi/git_forked/exampl
  image_encoder@64132[I]:🔧️                   workspace-id = ceb0455c-0b52-447b-8b00-77dd84
  image_encoder@64132[I]:🔧️                   zmq-identity = 1332449d-1aac-4038-bd33-22dd03
⠏ 8/10 waiting image_encoder audio_encoder to be ready...  image_encoder@64132[I]:                  
  image_encoder@64132[I]:           JINA@ 1[W]:You are using Jina version 2.1.7, however version 2.4.5 is available. You should consider upgrading via the "pip install --upgrade jina" command.
⠋ 8/10 waiting image_encoder audio_encoder to be ready...  image_encoder@64132[I]:Model already exists! Skipping.
  image_encoder@64132[I]:Vocab already exists! Skipping.
⠼ 8/10 waiting image_encoder audio_encoder to be ready...  audio_encoder@64144[I]:                  
  audio_encoder@64144[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  audio_encoder@64144[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  audio_encoder@64144[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  audio_encoder@64144[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  audio_encoder@64144[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  audio_encoder@64144[I]:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  audio_encoder@64144[I]:MMMMMMMMMMMMWxxxxxxxxxOMMMMMNxxxxxxxxx0MMMMMKddddddxkKWMMMMMMMMMMMMXOxdddxONMMMM
  audio_encoder@64144[I]:MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOllllllllllo0MMMMMMMM0olllllllllo0MM
  audio_encoder@64144[I]:MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOlllllllllllloWMMMMMdllllllllllllldM
  audio_encoder@64144[I]:MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOllllllllllllloMMMM0lllllllllllllllK
  audio_encoder@64144[I]:MMMMMMMMMMMMKllllllllldMMMMM0lllllllllxMMMMMOllllllllllllllKMMM0lllllllllllllllO
  audio_encoder@64144[I]:MMMMMMMMMMMMKllllllllldMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMollllllllllllllO
  audio_encoder@64144[I]:MWOkkkkk0MMMKlllllllllkMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMMxlllllllllllllO
  audio_encoder@64144[I]:NkkkkkkkkkMMKlllllllloMMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMMMWOdolllllllllO
  audio_encoder@64144[I]:KkkkkkkkkkNMKllllllldMMMMMMMMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  audio_encoder@64144[I]:MOkkkkkkk0MMKllllldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  audio_encoder@64144[I]:MMWX00KXMMMMXxk0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  audio_encoder@64144[I]:
  audio_encoder@64144[I]:▶️  /usr/local/bin/jina executor --uses config.yml --name audio_encoder --workspace /Users/sephi/git_forked/example-video-search --identity 81bae0e1-775a-43b0-9970-93f4aaec97b3 --workspace-id ad82497e-c4b9-4d35-89ee-aa1918bf1610 --zmq-identity f5ebfade-f5a4-4115-a521-4cbded8be07d --port-ctrl 53749 --uses-with {"traversal_paths": ["c"]} --port-in 53750 --port-out 53751 --hosts-in-connect --socket-in ROUTER_BIND --socket-out ROUTER_BIND --native --num-part 1 --dynamic-routing-out --dynamic-routing-in --runs-in-docker --upload-files --noblock-on-start
  audio_encoder@64144[I]:🔧️                            cli = executor                      
  audio_encoder@64144[I]:ctrl-with-ipc = False
  audio_encoder@64144[I]:daemon = False
  audio_encoder@64144[I]:disable-remote = False
  audio_encoder@64144[I]:docker-kwargs = None
  audio_encoder@64144[I]:dump-path =
  audio_encoder@64144[I]:🔧️             dynamic-routing-in = True                          
  audio_encoder@64144[I]:🔧️            dynamic-routing-out = True                          
  audio_encoder@64144[I]:entrypoint = None
  audio_encoder@64144[I]:env = None
  audio_encoder@64144[I]:expose-public = False
  audio_encoder@64144[I]:force = False
  audio_encoder@64144[I]:gpus = None
  audio_encoder@64144[I]:grpc-data-requests = False
  audio_encoder@64144[I]:host = 0.0.0.0
  audio_encoder@64144[I]:host-in = 0.0.0.0
  audio_encoder@64144[I]:host-out = 0.0.0.0
  audio_encoder@64144[I]:🔧️               hosts-in-connect = []                            
  audio_encoder@64144[I]:🔧️                       identity = 81bae0e1-775a-43b0-9970-93f4aa
  audio_encoder@64144[I]:install-requirements = False
  audio_encoder@64144[I]:k8s-connection-pool = True
  audio_encoder@64144[I]:k8s-namespace = None
  audio_encoder@64144[I]:log-config = /usr/local/lib/python3.7/site-
  audio_encoder@64144[I]:memory-hwm = -1
  audio_encoder@64144[I]:🔧️                           name = audio_encoder                 
  audio_encoder@64144[I]:🔧️                         native = True                          
  audio_encoder@64144[I]:🔧️               noblock-on-start = True                          
  audio_encoder@64144[I]:🔧️                       num-part = 1                             
  audio_encoder@64144[I]:on-error-strategy = IGNORE
  audio_encoder@64144[I]:pea-id = 0
  audio_encoder@64144[I]:pea-role = SINGLETON
  audio_encoder@64144[I]:🔧️                      port-ctrl = 53749                         
  audio_encoder@64144[I]:🔧️                        port-in = 53750                         
  audio_encoder@64144[I]:port-jinad = 8000
  audio_encoder@64144[I]:🔧️                       port-out = 53751                         
  audio_encoder@64144[I]:pull-latest = False
  audio_encoder@64144[I]:py-modules = None
  audio_encoder@64144[I]:quiet = False
  audio_encoder@64144[I]:quiet-error = False
  audio_encoder@64144[I]:quiet-remote-logs = False
  audio_encoder@64144[I]:routing-table = None
  audio_encoder@64144[I]:🔧️                 runs-in-docker = True                          
  audio_encoder@64144[I]:runtime-backend = PROCESS
  audio_encoder@64144[I]:runtime-cls = ZEDRuntime
  audio_encoder@64144[I]:🔧️                      socket-in = ROUTER_BIND                   
  audio_encoder@64144[I]:🔧️                     socket-out = ROUTER_BIND                   
  audio_encoder@64144[I]:ssh-keyfile = None
  audio_encoder@64144[I]:ssh-password = None
  audio_encoder@64144[I]:ssh-server = None
  audio_encoder@64144[I]:static-routing-table = False
  audio_encoder@64144[I]:timeout-ctrl = 5000
  audio_encoder@64144[I]:timeout-ready = 600000
  audio_encoder@64144[I]:🔧️                   upload-files = []                            
  audio_encoder@64144[I]:🔧️                           uses = config.yml                    
  audio_encoder@64144[I]:uses-metas = None
  audio_encoder@64144[I]:uses-requests = None
  audio_encoder@64144[I]:🔧️                      uses-with = {'traversal_paths': ['c']}    
  audio_encoder@64144[I]:volumes = None
  audio_encoder@64144[I]:🔧️                      workspace = /Users/sephi/git_forked/exampl
  audio_encoder@64144[I]:🔧️                   workspace-id = ad82497e-c4b9-4d35-89ee-aa1918
  audio_encoder@64144[I]:🔧️                   zmq-identity = f5ebfade-f5a4-4115-a521-4cbded
⠧ 8/10 waiting image_encoder audio_encoder to be ready...  audio_encoder@64144[I]:                  
  audio_encoder@64144[I]:           JINA@ 1[W]:You are using Jina version 2.1.7, however version 2.4.5 is available. You should consider upgrading via the "pip install --upgrade jina" command.
⠇ 8/10 waiting image_encoder audio_encoder to be ready...  image_encoder@64132[E]:Exception('the container fails to start, check the arguments or entrypoint') during <class 'jina.peapods.runtimes.container.ContainerRuntime'> initialization
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.5/lib/python3.9/site-packages/jina/peapods/peas/__init__.py", line 79, in run
    runtime = runtime_cls(
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.5/lib/python3.9/site-packages/jina/peapods/runtimes/container/__init__.py", line 49, in __init__
    raise Exception(
Exception: the container fails to start, check the arguments or entrypoint
⠋ 9/10 waiting audio_encoder to be ready...  audio_encoder@64144[I]:Model already exists! Skipping. 
  audio_encoder@64144[I]:Vocab already exists! Skipping.
⠼ 9/10 waiting audio_encoder to be ready...  audio_encoder@64144[E]:Exception('the container fails to start, check the arguments or entrypoint') during <class 'jina.peapods.runtimes.container.ContainerRuntime'> initialization
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.5/lib/python3.9/site-packages/jina/peapods/peas/__init__.py", line 79, in run
    runtime = runtime_cls(
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.5/lib/python3.9/site-packages/jina/peapods/runtimes/container/__init__.py", line 49, in __init__
    raise Exception(
Exception: the container fails to start, check the arguments or entrypoint
           Flow@63885[E]:Flow is aborted due to ['image_encoder', 'audio_encoder'] can not be started.
Traceback (most recent call last):
  File "/Users/sephi/git_forked/example-video-search/app.py", line 76, in <module>
    main()
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.5/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.5/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.5/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.5/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sephi/git_forked/example-video-search/app.py", line 58, in main
    with Flow.load_config('index-flow.yml', override_with=override_dict) as f:
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.5/lib/python3.9/site-packages/jina/flow/base.py", line 1115, in __enter__
    return self.start()
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.5/lib/python3.9/site-packages/jina/flow/base.py", line 1161, in start
    self._wait_until_all_ready()
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.5/lib/python3.9/site-packages/jina/flow/base.py", line 1245, in _wait_until_all_ready
    raise RuntimeFailToStart
jina.excepts.RuntimeFailToStart

```

</p>
</details>

**Comment by JoanFM** [comment]
Hey @sephib ,

could you please provide the jina version u are running it with?

**Comment by sephib** [comment]
Hi @JoanFM ,
Thx for the quick response. 
I've tried jina==2.4.5 and jina==2.1.7.
however, in the trace it always says that it is running with Jina version 2.1.7 - I thought it was related to the image that is running the executor.

**Comment by JoanFM** [comment]
Hey @sephib ,

may u try to remove the cache file under `$HOME/.jina/disk_cache.db` before running the version with jina 2.1.7?

**Comment by sephib** [comment]
Hi @JoanFM ,
Thx again for your time.
1. I reinstalled installed jina==2.1.7 in the virtual environment that I'm running
2. I deleted the  cache
  > rm ~/.jina/disk_cache.db 
3. deleted the workspace folder
4. rerun the code 
  > python app.py

Still getting an error regarding the `image_encoder`
The `audio_encoder` managed to start - but is stuck 
See log below
```sh
⠙ 8/10 waiting image_encoder audio_encoder to be ready...  audio_encoder@81541[I]:                  
  audio_encoder@81541[I]:           JINA@ 1[W]:You are using Jina version 2.1.7, however version 2.4.5 is available. You should consider upgrading via the "pip install --upgrade jina" command.
⠙ 8/10 waiting image_encoder audio_encoder to be ready...  audio_encoder@81541[I]:Model already exists! Skipping.
  audio_encoder@81541[I]:Vocab already exists! Skipping.
⠧ 8/10 waiting image_encoder audio_encoder to be ready...  image_encoder@81349[E]:Exception('the container fails to start, check the arguments or entrypoint') during <class 'jina.peapods.runtimes.container.ContainerRuntime'> initialization
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.8/lib/python3.9/site-packages/jina/peapods/peas/__init__.py", line 79, in run
    runtime = runtime_cls(
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.8/lib/python3.9/site-packages/jina/peapods/runtimes/container/__init__.py", line 49, in __init__
    raise Exception(
Exception: the container fails to start, check the arguments or entrypoint
⠏ 9/10 waiting audio_encoder to be ready...  audio_encoder@81541[I]:  audio_encoder@ 1[L]: Executor AudioCLIPEncoder started
⠙ 9/10 waiting audio_encoder to be ready...                                                         
⠋ 9/10 waiting audio_encoder to be ready...  audio_encoder@80923[W]:<class 'jina.peapods.runtimes.container.ContainerRuntime'> timeout after waiting for 600000ms, if your executor takes time to load, you may increase --timeout-ready
  audio_encoder@80923[W]:Pea is being closed before being ready. Most likely some other Pea in the Flow or Pod failed to start
⠋ 9/10 waiting audio_encoder to be ready...                                                         
```

**Comment by sephiartlist** [comment]
Update  @JoanFM  - still failing 
```sh
⠹ 9/10 waiting audio_encoder to be ready...  audio_encoder@80923[W]:Pea is being closed before being ready. Most likely some other Pea in the Flow or Pod failed to start
⠼ 9/10 waiting audio_encoder to be ready...  audio_encoder@80923[W]:Terminating process after waiting for readiness signal for graceful shutdown
           Flow@80923[E]:Flow is aborted due to ['image_encoder', 'audio_encoder'] can not be started.
Traceback (most recent call last):
  File "/Users/sephi/git_forked/example-video-search/app.py", line 76, in <module>
    main()
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.8/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.8/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.8/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.8/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sephi/git_forked/example-video-search/app.py", line 58, in main
    with Flow.load_config('index-flow.yml', override_with=override_dict) as f:
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.8/lib/python3.9/site-packages/jina/flow/base.py", line 1115, in __enter__
    return self.start()
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.8/lib/python3.9/site-packages/jina/flow/base.py", line 1161, in start
    self._wait_until_all_ready()
  File "/Users/sephi/git_forked/example-video-search/.direnv/python-3.9.8/lib/python3.9/site-packages/jina/flow/base.py", line 1245, in _wait_until_all_ready
    raise RuntimeFailToStart
jina.excepts.RuntimeFailToStart
```

**Comment by JoanFM** [comment]
can u share the logs of the process? It may be that the model is taking time to download the `AudioModel` and therefore is taking time there.

Maybe u can check the logs of the docker container trying to be started

**Comment by JoanFM** [comment]
May u also try to increase the `timeout-ready` parameter for the `audio_encoder`?

**Comment by nan-wang** [comment]
@sephib Sorry for the trouble but we can not reproduce this. From the logs you've provided, `AudioCLIPEncoder` has properly started,

> audio_encoder@64889[I]:Vocab already exists! Skipping.
⠇ 9/10 waiting audio_encoder to be ready...  audio_encoder@64889[I]:  audio_encoder@ 1[L]: Executor AudioCLIPEncoder started

I guess something goes wrong with the docker. Would you please give a try to run the following codes? Run it under `example-video-search` folder. 

```python
from jina import Document, Flow
import numpy as np

f = Flow().add(uses='jinahub+docker://AudioCLIPImageEncoder/v0.3', volumes='models:/workdir/.cache')
with f:
    resp = f.post(on='/index',
                  inputs=[Document(blob=np.random.randint(0, 256, (64, 64, 3), dtype=np.uint8))],
                  return_results=True)
print(f'embedding shape: {resp[0].docs[0].embedding.shape}')
```

**Comment by nan-wang** [comment]
Another favor we would like you to do is to offer the whole logs. You can get them by running this line and upload `stdout.log` and `stderr.log`.

```bash
python app.py >>stdout.log 2>stderr.log
```

**Comment by sephib** [comment]
Hi @nan-wang ,
Thx for your time and direction.
The `AudioCLIPImageEncoder` is running OK. the problem is with the `AudioCLIPEncoder` .
tried to run 
```python
    f = Flow().add(uses='jinahub+docker://AudioCLIPEncoder/v0.1', timeout_ready=3000)
    fake_log_mel_examples = np.random.random((2,96,64))
    doc_array = DocumentArray([Document(blob=fake_log_mel_examples)])
    with f:
        resp = f.post(on='test', inputs=doc_array, return_results=True)
        print(f'{resp}')
```
I can see the Container running - but the executor is failing 
```sh
⠏ 1/2 waiting executor0 to be ready...      executor0@34103[W]:<class 'jina.peapods.runtimes.container.ContainerRuntime'> timeout after waiting for 3000ms, if your executor takes time to load, you may increase --timeout-ready
      executor0@34103[W]:Pea is being closed before being ready. Most likely some other Pea in the Flow or Pod failed to start
⠇ 1/2 waiting executor0 to be ready...      executor0@34103[W]:Terminating process after waiting for readiness signal for graceful shutdown
⠏ 1/2 waiting executor0 to be ready...      executor0@34103[W]:Pea is being closed before being ready. Most likely some other Pea in the Flow or Pod failed to start
⠇ 1/2 waiting executor0 to be ready...      executor0@34103[W]:Terminating process after waiting for readiness signal for graceful shutdown
           Flow@34103[E]:Flow is aborted due to ['executor0'] can not be started.     
```
Any suggestions?

**Comment by nan-wang** [comment]
@sephib I see. Are you running on Mac OS X with the new M1 chip?

**Comment by sephib** [comment]
Hi @nan-wang ,
Thx for your time
trying to run this code
```python
    f = Flow().add(uses='jinahub+docker://AudioCLIPEncoder/v0.3', volumes='models:/workdir/.cache', timeout_ready=30000)
    fake_log_mel_examples = np.random.random((2,96,64))
    doc_array = DocumentArray([Document(blob=fake_log_mel_examples)])   
    with f:
        resp = f.post(on='/index',
                    inputs=[Document(blob=fake_log_mel_examples)],
                    return_results=True)
        print(f'Audio embedding shape: {resp[0].docs[0].embedding.shape}')
    with f:
        resp = f.post(on='test', inputs=doc_array, return_results=True)
        print(f'{resp}')
 ```
 I get the following error (I can see the containers running)
 ```sh
⠴ 1/2 waiting executor0 to be ready...      executor0@80627[W]:<class 'jina.peapods.runtimes.container.ContainerRuntime'> timeout after waiting for 30000ms, if your executor takes time to load, you may increase --timeout-ready
      executor0@80627[W]:Pea is being closed before being ready. Most likely some other Pea in the Flow or Pod failed to start
⠋ 1/2 waiting executor0 to be ready...      executor0@80627[W]:Terminating process after waiting for readiness signal for graceful shutdown
⠙ 1/2 waiting executor0 to be ready...      executor0@80627[W]:Pea is being closed before being ready. Most likely some other Pea in the Flow or Pod failed to start
⠼ 1/2 waiting executor0 to be ready...      executor0@80627[W]:Terminating process after waiting for readiness signal for graceful shutdown
           Flow@80627[E]:Flow is aborted due to ['executor0'] can not be started.                   

```

Any suggestions?

**Comment by winstonww** [comment]
Hi @sephib, 

Thanks for reporting this issue. Can you try increasing your docker resources to see if it helps?
<img width="1269" alt="Screen Shot 2021-11-19 at 3 04 54 PM" src="https://user-images.githubusercontent.com/13983591/142579761-2f083e44-50e7-4f8f-9c27-31f84768f0e0.png">

**Comment by sephib** [comment]
Hi @winstonww,
That did the trick  - thx!
I raised the `Memory` and the `Swap` - as you suggested -  and I was able to run the example.
Are there best practices regarding the docker image size that I can follow?

**Comment by sephib** [comment]
BTW - the link in the [README](https://github.com/jina-ai/example-video-search) to [How to Build Your First Jina App ](https://docs.jina.ai/chapters/my_first_jina_app/#how-to-build-your-first-jina-app) is broken - where should it lead to?

**Comment by sephib** [comment]
Another issue:
running the 
```bash
curl -X 'POST' 'http://localhost:45678/search'  \
-H 'accept: application/json'  \ 
-H 'Content-Type: application/json' 
-d '{"parameters":{"top_k": 5}, "data": ["a black dog and a spotted dog are fighting"]}'  \
```
resutls with 
> TypeError: match() got an unexpected keyword argument 'top_k'

**Comment by winstonww** [comment]
> Hi @winstonww,
> That did the trick - thx!
> I raised the Memory and the Swap - as you suggested - and I was able to run the example.
> Are there best practices regarding the docker image size that I can follow?

Glad to hear that the problem is fixed! Regarding docker resources, since the resource requirement really depends your use case (e.g. if you spin up multiple `AudioCLIPEncoder` then the resources needed would be more than if you just spin up one `AudioCLIPEncoder`), it's hard to give a minimum docker resource requirement. But it's always good to try increasing docker resource if `jinahub+docker` executors are not loading properly. We will add this to our FAQ/troubleshooting in our documentation.

**Comment by sephiartlist** [comment]
Thx again for all your  help . This issue can be closed from my end

**Comment by hokaso** [comment]
I have met same issus on ubuntu(linux), docker in linux can not  increase memory usage, what should I do?

![image](https://user-images.githubusercontent.com/26475781/210349208-111d708f-b417-4cab-8cb5-7b76c6b4dcc2.png)
